export * from './adminController.service';
import { AdminControllerService } from './adminController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './csrfController.service';
import { CsrfControllerService } from './csrfController.service';
export * from './degreeCourseController.service';
import { DegreeCourseControllerService } from './degreeCourseController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './passwordResetController.service';
import { PasswordResetControllerService } from './passwordResetController.service';
export * from './professorController.service';
import { ProfessorControllerService } from './professorController.service';
export * from './registrationController.service';
import { RegistrationControllerService } from './registrationController.service';
export * from './studentController.service';
import { StudentControllerService } from './studentController.service';
export * from './uniJourneySystemController.service';
import { UniJourneySystemControllerService } from './uniJourneySystemController.service';
export const APIS = [AdminControllerService, AuthControllerService, CsrfControllerService, DegreeCourseControllerService, NotificationControllerService, PasswordResetControllerService, ProfessorControllerService, RegistrationControllerService, StudentControllerService, UniJourneySystemControllerService];
