/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminResponse { 
    id?: string;
    username?: string;
    role?: string;
    firstName?: string;
    lastName?: string;
    dob?: string;
    age?: number;
    fiscalCode?: string;
    phone?: string;
    adminCode?: string;
    street?: string;
    city?: string;
    country?: string;
    zip?: string;
}

