/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DegreeCourseDto } from './degreeCourseDto';
import { ProfessorDto } from './professorDto';


export interface CourseDto { 
    name: string;
    type: CourseDto.TypeEnum;
    cfu?: number;
    yearOfStudy: number;
    professor?: ProfessorDto;
    degreeCourse?: DegreeCourseDto;
    degreeCourseName?: string;
}
export namespace CourseDto {
    export type TypeEnum = 'MATEMATICA' | 'INFORMATICA' | 'ECONOMIA' | 'FISICA' | 'CHIMICA' | 'DISEGNO' | 'IDRAULICA' | 'ING_MECCANICA' | 'ING_GESTIONALE' | 'ING_ELETTRICA' | 'ING_CIVILE' | 'ING_INFORMATICA' | 'ING_ELETTRONICA' | 'LINGUA_STRANIERA' | 'ALTRO';
    export const TypeEnum = {
        Matematica: 'MATEMATICA' as TypeEnum,
        Informatica: 'INFORMATICA' as TypeEnum,
        Economia: 'ECONOMIA' as TypeEnum,
        Fisica: 'FISICA' as TypeEnum,
        Chimica: 'CHIMICA' as TypeEnum,
        Disegno: 'DISEGNO' as TypeEnum,
        Idraulica: 'IDRAULICA' as TypeEnum,
        IngMeccanica: 'ING_MECCANICA' as TypeEnum,
        IngGestionale: 'ING_GESTIONALE' as TypeEnum,
        IngElettrica: 'ING_ELETTRICA' as TypeEnum,
        IngCivile: 'ING_CIVILE' as TypeEnum,
        IngInformatica: 'ING_INFORMATICA' as TypeEnum,
        IngElettronica: 'ING_ELETTRONICA' as TypeEnum,
        LinguaStraniera: 'LINGUA_STRANIERA' as TypeEnum,
        Altro: 'ALTRO' as TypeEnum
    };
}


