/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DegreeCourseId } from './degreeCourseId';


export interface DegreeCourseDto { 
    id?: DegreeCourseId;
    name: string;
    graduationClass: DegreeCourseDto.GraduationClassEnum;
    duration?: number;
}
export namespace DegreeCourseDto {
    export type GraduationClassEnum = 'BACHELOR' | 'MASTER' | 'PHD';
    export const GraduationClassEnum = {
        Bachelor: 'BACHELOR' as GraduationClassEnum,
        Master: 'MASTER' as GraduationClassEnum,
        Phd: 'PHD' as GraduationClassEnum
    };
}


