/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistrationRequest { 
    username: string;
    password: string;
    confirm: string;
    firstName: string;
    lastName: string;
    dob: string;
    fiscalCode: string;
    street: string;
    city: string;
    country: string;
    zip: string;
    phone: string;
    role: RegistrationRequest.RoleEnum;
    degreeCourse?: string;
    studyPlan?: string;
    ordering?: string;
}
export namespace RegistrationRequest {
    export type RoleEnum = 'ADMIN' | 'STUDENT' | 'PROFESSOR';
    export const RoleEnum = {
        Admin: 'ADMIN' as RoleEnum,
        Student: 'STUDENT' as RoleEnum,
        Professor: 'PROFESSOR' as RoleEnum
    };
}


